### ISSUE TITLE
Get PEAP Credentials with a computer that is connect to a PEAP Server by ethernet

### ISSUE THREAD

**Issue by FLKS07** [ash47/EnterpriseWifiPasswordRecover#17]
Hello, thanks for providing this cool project.
I'm having a issue where i have acess to a machine and when I try to get the credentials of a computer that is connected to ethert with PEAP, and I try to dump the PEAP password it doesn't work. 

Can you help me?

![imagem](https://github.com/ash47/EnterpriseWifiPasswordRecover/assets/67174547/df3a50e1-4b03-4340-ab77-270755064da6)

**Comment by FLKS07** [comment]
Sorry to forgot to note that i'm running this program through a USB Pen.

**Comment by ash47** [comment]
Per the instructions, you need to run it as either System, or the user who
entered the credentials -- there is instructions about how to run it as
system via psexec on the repo.
