### ISSUE TITLE
Win8 Issues

### ISSUE THREAD

**Issue by ghost** [ash47/EnterpriseWifiPasswordRecover#5]
I test this C# script on Windows 8 to find PEAP password from my School but all computers have Windows 8.1 Installed. So the script stop at Stage 2! Any Ideas? Does anyone know of another script that runs on win 8?

**Comment by ash47** [comment]
I've just now pushed another update, which MAY work, it was designed for Windows 10 -- however, it may use the same encryption mechanism in Windows 8.1
