### ISSUE TITLE
Windows 10 Files not found

### ISSUE THREAD

**Issue by ghost** [ash47/EnterpriseWifiPasswordRecover#6]
The following registry entry and following on disk directory is they are not present in the system:

HKEY_CURRENT_USER\Software\Microsoft\Wlansvc\UserData\Profiles\
C:\ProgramData\Microsoft\Wlansvc\Profiles\Interfaces\

the script has no output!
How can I do it?

**Comment by aarnaud** [comment]
Same for me

**Comment by ash47** [comment]
long time, no reply -- I've since pushed a new update that looks in some additional locations for the configuration files, let me know if this work :)
