### ISSUE TITLE
Can I use this if I have imported the registry file from another pc? 

### ISSUE THREAD

**Issue by Normalities** [ash47/EnterpriseWifiPasswordRecover#7]
Hi, I am wondering if I take the registry file (from the right path) and take it to another computer on another network, can I still decode the file and get the user/password? Thanks! (I also know the username and password to that computer user but don't have access to that computer anymore or the network) edit: at the moment the file is just on my desktop, I'm willing to properly import it into my own registry if that helps.

**Comment by ash47** [comment]
No.

The tool needs to be run in the correct contexts on the machine the wifi
was logged into on.

It's using a Windows encryption API that uses "environment variables" that
are different per account and per computer for the encrytion
